### ISSUE TITLE
21§

### ISSUE THREAD

**Issue by impulse72** [EvilPolygon/jun-test#1]
https://github.com/EvilPolygon/jun-test/blob/3025f63e986f8d893f122a455af9bbbc41c4b9f3/index.html#L8
зачем тебе джиквери, если будет реакт?

ваще пакеты лучше подключать через npm, а для сборки файлов использовать какой нить сборщик
самый популярный щас вебпак, мы тоже его юзаем

**Comment by EvilPolygon** [comment]
на ресурсе где обучался бутстрап объясняли что сам бутстрап использует jquery. но по факту я просто скопировал все четыре ссылки что бы ничего не сломалось. чисто на всякий случай. тем более используя CDN по быстродействию не сильно проиграю с сайтом такого размера. 

да и банально хз как именно npm подключить. займусь этим вопросом. исправлю

**Comment by EvilPolygon** [comment]
> https://github.com/EvilPolygon/jun-test/blob/3025f63e986f8d893f122a455af9bbbc41c4b9f3/index.html#L8
> 
> 
> зачем тебе джиквери, если будет реакт?
> ваще пакеты лучше подключать через npm, а для сборки файлов использовать какой нить сборщик
> самый популярный щас вебпак, мы тоже его юзаем

никак не получается подключить все через веб пак. я целый день на это убил и ничего не работает. я не понимаю что я делаю не так. потом с этим разберусь. пока буду делать через CDN
